- id: js-beautify
  name: js-beautify
  entry: js-beautify
  language: node
  files: \.js$
  args: []
  additional_dependencies: ['js-beautify@1.14.7']
  minimum_pre_commit_version: 2.7.1
  description: "Runs `js-beautify`"
